env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    needs: [Clone-down]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: ci/unit-test-app.sh
  Build:
    needs: [Clone-down]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: my-step
        run: chmod +x ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .


