name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Test
        run: ci/unit-test-app.sh
  Build:
    needs: Clone-down, Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
        - name: my-step
          run: chmod +x ci/build-app.sh
        - name: Upload Repo
          uses: actions/upload-artifact@v2
          with:
            name: code
            path: .


